import ThemeProvider from '@/components/ServerComponents/ThemeProvider';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import CssBaseline from '@/components/ServerComponents/CssBaseline';
import theme from '@/config/theme';
import { Providers } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' suppressHydrationWarning={true} >
			<ThemeProvider theme={theme}>
				<CssBaseline />
				<body className={inter.className}>
					<Providers>
						{children}
					</Providers>
				</body>
			</ThemeProvider>
		</html>
	)
}
